// Hero Siege S10 packet stat IDs. Numeric IDs are the exact current config
// value; rules also persist the semantic key so a future season can migrate.
//
// Coverage is the union of every top-level numeric/boolean key in the current
// named-item itemBaseStatStruct, the current in-game loot filter, the current
// game's ReturnStatName switch, and independently valued stat IDs observed in
// pickup packets. Descriptor slots 10-15 and datamine metadata keys 431/432
// are intentionally excluded. A transparent unlabeled entry is preferable to
// silently hiding a stat whose meaning is uncertain.
//
// Keep flat projectile speed (70) distinct from percent projectile speed (71).
const RAW_ITEM_STATS = [
  [25, "movement_speed", "Movement Speed"],
  [26, "phasing", "Phasing"],
  [27, "jumping_power", "Jumping Power"],
  [28, "enhanced_damage", "Enhanced Damage"],
  [29, "enhanced_defense", "Enhanced Defense"],
  [30, "enhanced_damage_per_level", "Enhanced Damage per Level"],
  [31, "enhanced_defense_per_level", "Enhanced Defense per Level"],
  [33, "strength", "Strength"],
  [34, "strength_per_level", "Strength per Level"],
  [36, "dexterity", "Dexterity"],
  [37, "dexterity_per_level", "Dexterity per Level"],
  [39, "energy", "Energy"],
  [40, "energy_per_level", "Energy per Level"],
  [42, "intelligence", "Intelligence"],
  [43, "intelligence_per_level", "Intelligence per Level"],
  [45, "armor", "Armor"],
  [46, "armor_per_level", "Armor per Level"],
  [48, "vitality", "Vitality"],
  [49, "vitality_per_level", "Vitality per Level"],
  [51, "all_stats", "All Attributes"],
  [52, "max_hp", "Life"],
  [53, "hp_p", "Increased Life"],
  [54, "hp_per_level", "Life per Level"],
  [55, "health_regen", "Life Regeneration"],
  [57, "life_per_hit", "Life Stolen per Hit"],
  [58, "hp_per_second", "Life per Second"],
  [59, "hp_kill", "Life after Kill"],
  [60, "max_mana", "Mana"],
  [61, "mana_p", "Increased Mana"],
  [62, "mana_per_level", "Mana per Level"],
  [63, "mana_regen", "Mana Regeneration"],
  [64, "mana_per_hit", "Mana Stolen per Hit"],
  [65, "mana_per_second", "Mana per Second"],
  [66, "mana_kill", "Mana after Kill"],
  [67, "attack_range", "Attack Range"],
  [68, "attack_speed", "Increased Attack Speed"],
  [70, "projectile_speed", "Projectile Speed (flat)"],
  [71, "projectile_speed_percent", "Projectile Speed (%)"],
  [72, "critical_chance", "Critical Strike Chance"],
  [73, "critical_damage", "Critical Strike Damage"],
  [74, "attack_rating", "Attack Rating"],
  [75, "attack_rating_p", "Increased Attack Rating"],
  [76, "attack_rating_per_level", "Attack Rating per Level"],
  [77, "piercing", "Piercing Attack"],
  [78, "slow_target", "Slow Target"],
  [79, "extra_dmg_to_stunned_percent", "Extra Damage to Stunned Monsters"],
  [80, "extra_dmg_to_bleeding_percent", "Extra Damage to Bleeding Monsters"],
  [81, "extra_dmg_to_deep_frozen_percent", "Extra Damage to Deep Frozen Monsters"],
  [82, "extra_dmg_to_poisoned_percent", "Extra Damage to Poisoned Monsters"],
  [83, "extra_dmg_to_burning_percent", "Extra Damage to Burning Monsters"],
  [84, "extra_dmg_to_stasis_percent", "Extra Damage to Monsters with Stasis"],
  [85, "extra_dmg_to_shadowburn_percent", "Extra Damage to Monsters with Shadowburn"],
  [86, "extra_dmg_to_frostbitten_percent", "Extra Damage to Frostbitten Monsters"],
  [87, "extra_dmg_to_monsters_afflicted_with_ailments_percent", "Extra Damage to Monsters with Ailments"],
  [94, "ignore_defense", "Ignore Target Defense"],
  [95, "deadly_blow", "Deadly Blow Chance"],
  [97, "crushing_blow", "Crushing Blow Chance"],
  [99, "open_wounds", "Open Wound Chance"],
  [101, "skill_damage", "Magic Skill Damage"],
  [103, "attack_dmg_based_on_level_flat", "Physical Damage per Level"],
  [104, "bleed_tick_frequency_percent", "Bleed Tick Frequency"],
  [105, "poison_tick_frequency_percent", "Poison Tick Frequency"],
  [106, "burning_tick_frequency_percent", "Burning Tick Frequency"],
  [107, "stasis_tick_frequency_percent", "Stasis Tick Frequency"],
  [108, "shadow_burn_tick_frequency_percent", "Shadowburn Tick Frequency"],
  [109, "frost_bite_tick_frequency_percent", "Frostbite Tick Frequency"],
  [110, "ailment_tick_frequency_percent", "Ailment Tick Frequency"],
  [111, "explosion_damage", "Explosion Damage"],
  [112, "explosion_skills", "Explosion Skills"],
  [128, "physical_damage", "Physical Damage (flat)"],
  [129, "attack_damage", "Attack Damage"],
  [132, "fire_damage", "Fire Damage (flat)"],
  [133, "fire_damage_f", "Fire Skill Damage (flat)"],
  [134, "fire_damage_p", "Fire Skill Damage"],
  [135, "ignore_fire_resist", "Enemy Fire Resistance"],
  [136, "cold_damage", "Cold Damage (flat)"],
  [137, "cold_damage_f", "Cold Skill Damage (flat)"],
  [138, "cold_damage_p", "Cold Skill Damage"],
  [139, "ignore_cold_resist", "Enemy Cold Resistance"],
  [140, "magic_damage", "Arcane Damage (flat)"],
  [141, "magic_damage_f", "Arcane Skill Damage (flat)"],
  [142, "magic_damage_p", "Arcane Skill Damage"],
  [143, "ignore_magic_resist", "Enemy Arcane Resistance"],
  [144, "lightning_damage", "Lightning Damage (flat)"],
  [145, "lightning_damage_f", "Lightning Skill Damage (flat)"],
  [146, "lightning_damage_p", "Lightning Skill Damage"],
  [147, "ignore_lightning_resist", "Enemy Lightning Resistance"],
  [148, "poison_damage", "Poison Damage (flat)"],
  [149, "poison_damage_f", "Poison Skill Damage (flat)"],
  [150, "poison_damage_p", "Poison Skill Damage"],
  [151, "ignore_poison_resist", "Enemy Poison Resistance"],
  [152, "ignore_all_resists", "All Enemy Resistances"],
  [153, "magic_skill_dmg_flat", "Magic Skill Damage (flat)"],
  [154, "defense", "Defense"],
  [155, "defense_p", "Increased Defense"],
  [156, "defense_per_level", "Defense per Level"],
  [157, "block_rate", "Block Chance"],
  [158, "block_rating", "Increased Block Chance"],
  [159, "reduction", "Physical Damage Reduction"],
  [160, "magic_reduction", "Magic Damage Reduction"],
  [161, "all_reduction", "All Damage Reduction"],
  [162, "damage_reduced", "Flat Damage Reduction"],
  [163, "phys_taken_cold", "Physical Damage Taken as Cold"],
  [164, "phys_taken_fire", "Physical Damage Taken as Fire"],
  [165, "phys_taken_arcane", "Physical Damage Taken as Arcane"],
  [166, "phys_taken_lightning", "Physical Damage Taken as Lightning"],
  [167, "damage_taken_mana", "Damage Taken to Mana"],
  [168, "damage_taken_life", "Damage Taken to Life"],
  [169, "defense_vs_missile", "Defense vs Missiles"],
  [170, "faster_hit_recovery", "Faster Hit Recovery"],
  [171, "damage_return", "Damage Returned to Attacker"],
  [173, "all_resistance", "All Resistances"],
  [174, "max_all_resistances", "Maximum All Resistances"],
  [175, "fire_resistance", "Fire Resistance"],
  [176, "max_fire_resistance", "Maximum Fire Resistance"],
  [177, "cold_resistance", "Cold Resistance"],
  [178, "max_cold_resistance", "Maximum Cold Resistance"],
  [179, "lightning_resistance", "Lightning Resistance"],
  [180, "max_lightning_resistance", "Maximum Lightning Resistance"],
  [181, "arcane_resistance", "Arcane Resistance"],
  [182, "max_magic_resistance", "Maximum Arcane Resistance"],
  [183, "poison_resistance", "Poison Resistance"],
  [184, "max_poison_resistance", "Maximum Poison Resistance"],
  [191, "fire_absorb", "Fire Absorb"],
  [192, "cold_absorb", "Cold Absorb"],
  [193, "poison_absorb", "Poison Absorb"],
  [194, "lightning_absorb", "Lightning Absorb"],
  [195, "arcane_absorb", "Arcane Absorb"],
  [196, "faster_cast_rate", "Faster Cast Rate"],
  [198, "cooldown_reduction", "Skill Haste"],
  [199, "cooldown_reduction_potion", "Flask Skill Haste"],
  [200, "mana_costs", "Mana Costs"],
  [201, "all_talents", "All Skills"],
  [202, "singular_skill", "Granted Skill (skill ID)"],
  [222, "physical_skills", "Physical Skills"],
  [223, "cold_skills", "Cold Skills"],
  [224, "arcane_skills", "Arcane Skills"],
  [225, "fire_skills", "Fire Skills"],
  [226, "lightning_skills", "Lightning Skills"],
  [227, "poison_skills", "Poison Skills"],
  [250, "ailment_damage_percent", "Ailment Damage"],
  [281, "light_radius", "Light Radius"],
  [282, "exp_gain", "Experience Gain"],
  [283, "exp_gain_below", "Experience Gain below Level 100"],
  [284, "magic_find", "Magic Find"],
  [285, "magic_find_per_level", "Magic Find per Level"],
  [286, "extra_gold", "Extra Gold"],
  [287, "half_freeze_duration", "Half Freeze Duration"],
  [288, "cannot_be_frozen", "Cannot Be Frozen"],
  [289, "poison_length_reduced", "Poison Length Reduction"],
  [290, "merchant_prices", "Merchant Prices"],
  [327, "summon_life_p", "Summon Life"],
  [328, "summon_reduction", "Summon Damage Reduction"],
  [329, "summon_resists", "Summon Resistances"],
  [330, "summon_amount", "Additional Summons"],
  [331, "summon_skills", "Summon Skills"],
  [332, "summon_damage_p", "Summon Damage"],
  [333, "summon_attack_speed", "Summon Attack Speed"],
  [334, "summon_movement_speed", "Summon Movement Speed"],
  [335, "sentry_skills", "Sentry Skills"],
  [336, "sentry_damage_p", "Sentry Damage"],
  [337, "sentry_amount", "Additional Sentries"],
  [338, "sentry_attack_speed", "Sentry Attack Speed"],
  [339, "sentry_duration", "Sentry Duration"],
  [437, "explosion_aoe", "Explosion Area of Effect"],
  [0, "unholy_none", "Unholy Stat"],
  [1, "stat_1", "Stat #1 (unlabeled)"],
  [2, "stat_2", "Stat #2 (unlabeled)"],
  [20, "socketed_flat", "Sockets"],
  [21, "class_skill_class_id", "Class ID for Class-Skill Bonus"],
  [22, "attack_dmg_base", "Base Attack Damage"],
  [23, "attacks_per_second_base", "Base Attacks per Second"],
  [24, "stat_24", "Stat #24 (unlabeled)"],
  [32, "strength_increase_percent", "Increased Strength"],
  [35, "dexterity_increase_percent", "Increased Dexterity"],
  [38, "energy_increase_percent", "Increased Energy"],
  [41, "intelligence_increase_percent", "Increased Intelligence"],
  [44, "armor_increase_percent", "Increased Armor"],
  [47, "vitality_increase_percent", "Increased Vitality"],
  [50, "all_attributes_percent", "Increased All Attributes"],
  [69, "total_attack_speed_percent", "Total Attack Speed"],
  [88, "extra_fire_dmg_to_burning_percent", "Extra Fire Damage to Burning Monsters"],
  [89, "extra_cold_dmg_to_frostbitten_percent", "Extra Cold Damage to Frostbitten Monsters"],
  [90, "extra_poison_dmg_to_poisoned_percent", "Extra Poison Damage to Poisoned Monsters"],
  [91, "extra_arcane_dmg_to_shadowburn_percent", "Extra Arcane Damage to Shadowburn Monsters"],
  [92, "extra_lightning_dmg_to_stasis_percent", "Extra Lightning Damage to Monsters with Stasis"],
  [93, "extra_physical_dmg_to_bleeding_percent", "Extra Physical Damage to Bleeding Monsters"],
  [96, "deadly_blow_effect", "Deadly Blow Damage"],
  [102, "monsters_rest_in_peace", "Monsters Rest in Peace"],
  [113, "when_attacking_spell_id", "When Attacking Proc: Spell ID"],
  [114, "when_attacking_skill_level", "When Attacking Proc: Skill Level"],
  [115, "when_attacking_chance_percent", "When Attacking Proc: Chance (%)"],
  [116, "when_striking_spell_id", "When Striking Proc: Spell ID"],
  [117, "when_striking_skill_level", "When Striking Proc: Skill Level"],
  [118, "when_striking_chance_percent", "When Striking Proc: Chance (%)"],
  [122, "after_kill_spell_id", "After Kill Proc: Spell ID"],
  [123, "after_kill_skill_level", "After Kill Proc: Skill Level"],
  [124, "after_kill_chance_percent", "After Kill Proc: Chance (%)"],
  [125, "when_casting_spell_id", "When Casting Proc: Spell ID"],
  [126, "when_casting_skill_level", "When Casting Proc: Skill Level"],
  [127, "when_casting_chance_percent", "When Casting Proc: Chance (%)"],
  [130, "projectile_damage_increase", "Projectile Damage"],
  [172, "damage_from_resist", "Damage from Resistances"],
  [185, "when_struck_spell_id", "When Struck Proc: Spell ID"],
  [186, "when_struck_skill_level", "When Struck Proc: Skill Level"],
  [187, "when_struck_chance_percent", "When Struck Proc: Chance (%)"],
  [188, "after_blocking_spell_id", "After Blocking Proc: Spell ID"],
  [189, "after_blocking_skill_level", "After Blocking Proc: Skill Level"],
  [190, "after_blocking_chance_percent", "After Blocking Proc: Chance (%)"],
  [197, "total_faster_cast_rate_percent", "Total Faster Cast Rate"],
  [203, "grant_spell_level", "Granted Skill Level"],
  [204, "grant_spell_class_id", "Granted Skill Class ID"],
  [205, "grant_spell_2_id", "Granted Skill 2: Spell ID"],
  [206, "grant_spell_2_level", "Granted Skill 2: Level"],
  [207, "grant_spell_2_class_id", "Granted Skill 2: Class ID"],
  [208, "grant_spell_3_id", "Granted Skill 3: Spell ID"],
  [209, "grant_spell_3_level", "Granted Skill 3: Level"],
  [210, "grant_spell_3_class_id", "Granted Skill 3: Class ID"],
  [211, "grant_spell_4_id", "Granted Skill 4: Spell ID"],
  [212, "grant_spell_4_level", "Granted Skill 4: Level"],
  [220, "to_subskills_flat", "Subskills"],
  [221, "random_skill_element_flat", "Random Skill Element"],
  [228, "intelligence_converted_to_magic_skill_dmg_percent", "Intelligence added as Magic Skill Damage"],
  [229, "intelligence_converted_to_lightning_skill_dmg_percent", "Intelligence added as Lightning Skill Damage"],
  [230, "intelligence_converted_to_fire_skill_dmg_percent", "Intelligence added as Fire Skill Damage"],
  [231, "intelligence_converted_to_cold_skill_dmg_percent", "Intelligence added as Cold Skill Damage"],
  [232, "intelligence_converted_to_arcane_skill_dmg_percent", "Intelligence added as Arcane Skill Damage"],
  [234, "vitality_converted_to_attack_dmg_percent", "Vitality added as Attack Damage"],
  [235, "vitality_converted_to_magic_skill_dmg_percent", "Vitality added as Magic Skill Damage"],
  [241, "energy_converted_to_magic_skill_dmg_percent", "Energy added as Magic Skill Damage"],
  [242, "energy_converted_to_lightning_skill_dmg_percent", "Energy added as Lightning Skill Damage"],
  [244, "energy_converted_to_cold_skill_dmg_percent", "Energy added as Cold Skill Damage"],
  [247, "armor_converted_to_magic_skill_dmg_percent", "Armor added as Magic Skill Damage"],
  [248, "armor_converted_to_attack_dmg_percent", "Armor added as Attack Damage"],
  [249, "faster_cast_rate_percent_converted_to_movement_speed_percent", "Faster Cast Rate added as Movement Speed"],
  [251, "bleed_damage_percent", "Bleed Damage"],
  [252, "poison_damage_percent", "Poison Damage"],
  [253, "stasis_damage_percent", "Stasis Damage"],
  [254, "shadowburn_damage_percent", "Shadowburn Damage"],
  [255, "frostbite_damage_percent", "Frostbite Damage"],
  [256, "burning_damage_percent", "Burning Damage"],
  [257, "ailment_critical_strike_chance_percent", "Ailment Critical Strike Chance"],
  [258, "ailment_critical_strike_dmg_percent", "Ailment Critical Strike Damage"],
  [259, "stat_259", "Stat #259 (unlabeled)"],
  [260, "stat_260", "Stat #260 (unlabeled)"],
  [261, "buffing_aura_effectiveness_increased_percent", "Buffing Aura Effectiveness"],
  [262, "buffing_aura_range_increased_percent", "Buffing Aura Range"],
  [263, "crushing_blow_stacks_flat", "Maximum Crushing Blow Stacks"],
  [264, "life_replenish_when_blocking_percent", "Life Replenished when Blocking"],
  [265, "chance_to_replenish_life_when_blocking_percent", "Chance to Replenish Life when Blocking"],
  [266, "orbital_projectile_duration_increased_percent", "Orbital Projectile Duration"],
  [267, "stat_267", "Stat #267 (unlabeled)"],
  [268, "aoe_size_percent", "Area of Effect Size"],
  [269, "aoe_damage_percent", "Area of Effect Damage"],
  [270, "melee_skills_flat", "Melee Skills"],
  [271, "ranged_skills_flat", "Ranged Skills"],
  [272, "orbit_skills_flat", "Orbiting Skills"],
  [273, "aoe_skills_flat", "Area of Effect Skills"],
  [274, "projectile_skills_flat", "Projectile Skills"],
  [275, "self_inflicted_damage_from_attacking_flat", "Self-Damage when Attacking"],
  [276, "self_inflicted_chance_when_attacking", "Chance to Self-Damage when Attacking"],
  [277, "self_inflicted_damage_from_casting_flat", "Self-Damage when Casting"],
  [278, "self_inflicted_chance_when_casting_flat", "Chance to Self-Damage when Casting"],
  [279, "dmg_taken_over_time_percent", "Damage Taken over Time (%)"],
  [280, "dmg_taken_over_time_seconds", "Damage Taken over Time Duration"],
  [291, "double_jump", "Double Jump"],
  [292, "stat_292", "Stat #292 (unlabeled)"],
  [293, "mirror_ring_none", "Mirrors Other Ring"],
  [294, "skill_movement_diminish_percent", "Skill Movement Diminish Reduction"],
  [295, "enjoyer_tracker_stat", "Enjoyer Tracker Stat"],
  [296, "orbiting_relic_radius_increase_percent", "Orbiting Relic Radius"],
  [297, "orbiting_relic_amount_flat", "Orbiting Relic Amount"],
  [298, "orbiting_relic_damage_flat", "Orbiting Relic Damage"],
  [300, "orbiting_relic_execute_below_health_percent", "Orbiting Relic Execute Threshold"],
  [301, "orbiting_relic_size_percent", "Orbiting Relic Size"],
  [302, "follower_relic_damage_flat", "Follower Relic Damage (flat)"],
  [303, "follower_relic_damage_percent", "Follower Relic Damage"],
  [304, "follower_relic_attack_speed_percent", "Follower Relic Attack Speed"],
  [305, "follower_relic_projectiles_flat", "Follower Relic Projectiles"],
  [307, "proc_non_buff_relic_chance_percent", "Non-Buff Proc Relic Chance"],
  [308, "effectiveness_of_non_buff_proc_relics_percent", "Non-Buff Proc Relic Effectiveness"],
  [309, "skill_relic_damage_flat", "Skill Relic Damage (flat)"],
  [310, "skill_relic_damage_percent", "Skill Relic Damage"],
  [311, "skill_relic_projectiles_flat", "Skill Relic Projectiles"],
  [312, "skill_relic_projectile_size_percent", "Skill Relic Projectile Size"],
  [313, "skill_relic_additional_casts", "Additional Skill Relic Casts"],
  [314, "skill_relic_cooldown_percent", "Skill Relic Cooldown"],
  [315, "grant_aura_id", "Granted Aura ID"],
  [316, "grant_aura_level", "Granted Aura Level"],
  [319, "grant_aura_1_id", "Granted Aura 1: ID"],
  [320, "grant_aura_1_level", "Granted Aura 1: Level"],
  [321, "grant_aura_2_id", "Granted Aura 2: ID"],
  [322, "grant_aura_2_level", "Granted Aura 2: Level"],
  [323, "grant_aura_3_id", "Granted Aura 3: ID"],
  [324, "grant_aura_3_level", "Granted Aura 3: Level"],
  [325, "grant_aura_4_id", "Granted Aura 4: ID"],
  [326, "grant_aura_4_level", "Granted Aura 4: Level"],
  [340, "guardian_damage_percent", "Guardian Damage"],
  [341, "guardian_additional_attack_percent", "Guardian Additional Attack Chance"],
  [342, "guardian_attack_speed_percent", "Guardian Attack Speed"],
  [343, "guardian_attack_range_percent", "Guardian Attack Range"],
  [344, "guardian_duration_percent", "Guardian Duration"],
  [390, "potion_charges_per_use", "Potion Effect Duration"],
  [393, "potion_max_charges", "Maximum Potion Charges"],
  [396, "potion_cooldown", "Flask Cooldown"],
  [411, "damage_redirected_to_octa", "Damage Redirected to Octa"],
  [412, "less_dmg_with_cd_skills_percent", "Less Damage with Cooldown Skills"],
  [416, "stat_416", "Stat #416 (unlabeled)"],
  [417, "projectile_size_increase", "Projectile Size"],
  [418, "stat_418", "Stat #418 (unlabeled)"],
  [419, "grant_subskills_spell_id", "Granted Subskills: Spell ID"],
  [420, "grant_subskills_level", "Granted Subskills: Level"],
  [444, "stat_444", "Stat #444 (unlabeled)"],
  [445, "stat_445", "Stat #445 (unlabeled)"],
  [447, "stat_447", "Stat #447 (unlabeled)"],
  [448, "stat_448", "Stat #448 (unlabeled)"],
  [467, "cold_resist_converted_to_cold_skill_dmg_percent", "Cold Resistance converted to Cold Skill Damage"],
  [469, "poison_resist_converted_to_poison_skill_dmg_percent", "Poison Resistance converted to Poison Skill Damage"],
  [471, "spell_aoe_radius_percent", "Spell Area of Effect Radius"],
  [472, "attack_aoe_radius_percent", "Attack Area of Effect Radius"],
  [474, "dmg_returned_to_attacker_percent", "Damage Returned to Attacker (%)"],
  [475, "suppress_spell_hits", "Spell Hit Suppression Chance"],
].sort(([left], [right]) => left - right);

export const ITEM_STATS = Object.freeze(
  RAW_ITEM_STATS.map(([id, key, label]) => Object.freeze({ id, key, label })),
);

const ITEM_STAT_BY_ID = new Map(ITEM_STATS.map((stat) => [stat.id, stat]));

export function statLabel(id) {
  const numericId = Number(id);
  return ITEM_STAT_BY_ID.get(numericId)?.label ?? `Stat #${id}`;
}
